### ISSUE TITLE
Sitemaps could be compressed and should be decompressed if so

### ISSUE THREAD

**Issue by lakhman** [tzfrs/googlesitemapparser#2]
For example checkout: http://www.sainsburys.co.uk/robots.txt

```
Sitemap: http://www.sainsburys.co.uk/wcsstore/robots/sitemap_10151_1.xml.gz
Sitemap: http://www.sainsburys.co.uk/wcsstore/robots/sitemap_10151_2.xml.gz
Sitemap: http://www.sainsburys.co.uk/wcsstore/robots/sitemap_10151_3.xml.gz
Sitemap: http://www.sainsburys.co.uk/wcsstore/robots/sitemap_10151_4.xml.gz
Sitemap: http://www.sainsburys.co.uk/sitemap.xml
```

Should also check against the robots.txt to obey disallow rules and pickup other sitemaps if specified.

Thanks! Awesome Project! +1

**Comment by kobelobster** [comment]
Thanks. Glad you like it!

Sounds like a cool idea.  :) Will assign to myself and do it when I got time.

You mean, that I parse the sitemaps from the robots.txt and then simply return the contents, right? Do you have another example of this use besides sainsbury that uses gzip compression? simplexml_load_string tells me that the xml is not valid. But maybe I'll use DOMDocument in the future.

**Comment by lakhman** [comment]
Pretty much yeah, use regex to grab the sitemap, check if it's zipped, if so unzip, and return the contents.

I might fork and have a play when I get a chance! Thanks!

**Comment by kobelobster** [comment]
Yep, that's what I'm actually doing haha. Have just to do the unzipping part now, the rest already works. But have to do the rest tomorrow.

**Comment by Lakhman** [comment]
Awesome! :) I'll wait, Looking forward to having a play with it!

**Comment by kobelobster** [comment]
I implemented now a way to scan for robots.txt with the method parseFromRobots.txt

The library now also supports text sitemaps.

f77ae4d509fa793b60cbf1dc2419f659aa0535e2
