### ISSUE TITLE
Useful to have the priority and lastmod for a sitemap

### ISSUE THREAD

**Issue by lakhman** [tzfrs/googlesitemapparser#3]
Just had a play with the library, It's awesome and works very well for large sitemaps.

I have an improvment idea, it would be nice to have the priority and lastmod of the sitemap also, as users may want to only crawl pages that have changed or off a certain priority. (High priority = daily crawls, low priority = weekly crawls).

I was hoping to use this to read a sitemap, insert it into a db (url, priority, lastmod) - so I don't have to keep hitting the server. Then I would continue to process it as required by my application. So having it return an array (or an option of returning the full array or url only) would be really useful.

+1 ;)

**Comment by lakhman** [comment]
Awesome! Thank You!

**Comment by kobelobster** [comment]
Ah, I just saw, that I only included the priority, not the lastmod. :/ Will also check this.

**Comment by lakhman** [comment]
Ha! was just about to play with it! no probs! thanks for the update!

**Comment by kobelobster** [comment]
Now you have both information! Hope it helps you!
